[phases.setup]
nixPkgs = ["chromium", "nodejs_18"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "PUPPETEER_EXECUTABLE_PATH=$(which chromium-browser || which chromium || which google-chrome-stable) node index.js"
